##################################################################################################
# service C
##################################################################################################

apiVersion: v1
kind: Service
metadata:
  name: svc-c
  labels:
    app: svc-c
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: http
#    nodePort: 32000
#  type: NodePort
  selector:
    app: svc-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-c
  template:
    metadata:
      labels:
        app: svc-c
        version: v1
        role: normal
    spec:
      containers:
      - name: svc-c
        image: jiuchen1986/go-micro-service:full
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: TEST_SERVICE_NAME
          value: svc-c
        - name: TEST_SERVICE_VERSION
          value: v1              
---
