# Simulate 10 percent failure of the svc-d normal by inject 10 percent abort from svc-d normal to svc-g

apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: abort-svc-d-10p
  namespace: default
spec:
  destination:
    name: svc-g
  match:
    source:
      name: svc-d
      labels:
        version: v1
        role: normal
  httpFault:
    abort:
      httpStatus: 400
      percent: 10
  precedence: 10
  route:
  - labels:
      version: v1
      role: normal
---

