# a quota counting each request with dimensions of the versions and the roles

apiVersion: config.istio.io/v1alpha2
kind: quota
metadata:
  name: requestcount-role-version
  namespace: istio-system
spec:
  dimensions:
    source: source.labels["app"] | source.service | "unknown"
    sourceRole: source.labels["role"] | "unknown"
    sourceVersion: source.labels["version"] | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    destinationRole: destination.labels["role"] | "unknown"
    destinationVersion: destination.labels["version"] | "unknown"
---


# memquota to limit the request rate from each source to svc-d
# this is enabled by only ruling the quota instances with both source and destination dimensions, and
# with the destination of svc-d to this quota

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-from-each-to-svc-d-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-role-version.quota.istio-system
    # default rate limit for request from each source to svc-d is 80qps
    maxAmount: 80
    validDuration: 1s

---

# Ruling the requestcount-role-version instances with the destination.service or destination.labels["app"] as svc-d
# to be handled by the memquota "rate-limit-to-svc-d-handler"

apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: rule-requestcount-from-each-to-svc-d
  namespace: istio-system
spec:
  match: destination.labels["app"] == "svc-d" || destination.service == "svc-d"
  actions:
  - handler: rate-limit-from-each-to-svc-d-handler.memquota
    instances:
    - requestcount-role-version.quota
---

