# memquota to limit the request rate from each source to svc-d
# this is enabled by only ruling the quota instances with both source and destination dimensions, and
# with the destination of svc-d to this quota

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-from-each-to-svc-d-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-role-version.quota.istio-system
    # default rate limit for request from each to svc-d is 80qps
    maxAmount: 80
    validDuration: 1s

---

