# memquota to limit the total request rate from svc-b
# this is enabled by ruled the request with source as the svc-b to thie memquota
# a override is also defined to limit the request rate from svc-b to svc-d

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-from-svc-b-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-role-version.quota.istio-system
    # default total rate limit for requests from svc-b is 160qps
    maxAmount: 160
    validDuration: 1s
    # The first matching override is applied.
    # A requestcount-role-version instance is checked against override dimensions.
    overrides:
    # The following override applies to traffic from svc-b with role normal,
    # destined for the svc-d service with role normal.
    # The key names of the dimenstions will be matched with the key names defined in the corresponding quota
    # Exact matching will be applied
    - dimensions:
        destination: svc-d
        destinationRole: normal
        source: svc-b
        sourceRole: normal
      maxAmount: 80
      validDuration: 1s

---

