# memquota to limit the total request rate to svc-d
# this is enabled by only ruling the quota instances without source dimensions, and
# with the destination of svc-d to this quota

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-to-svc-d-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-role-version-no-source.quota.istio-system
    # default total rate limit for requests to svc-d is 200qps
    maxAmount: 200
    validDuration: 1s

---

