# memquota to limit the total request rate to svc-d
# this is enabled by only ruling the quota instances without destination dimensions, and
# with the destination of svc-d to this quota

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-from-each-to-svc-d-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-role-version.quota.istio-system
    # default total rate limit for requests to svc-d is 50qps
    maxAmount: 50
    validDuration: 1s

---

