# memquota to limit the total request rate to svc-d
# and the request rate from svc-f to svc-d

apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit-to-svc-d-handler
  namespace: istio-system
spec:
  quotas:
  - name: requestcount-to-svc-d.quota.istio-system
    # default total rate limit for requests to svc-d is 200qps
    maxAmount: 200
    validDuration: 1s
    # The first matching override is applied.
    # A requestcount-svc-d instance is checked against override dimensions.
    overrides:
    # The following override applies to traffic from svc-b with role normal,
    # destined for the svc-d service with role normal.
    # The key names of the dimenstions will be matched with the key names defined in the corresponding quota
    # Exact matching will be applied
    - dimensions:
        destination: svc-d
        destinationRole: normal
        source: svc-b
        sourceRole: normal
      maxAmount: 100
      validDuration: 1s

---

